# JazzOnlineCmnConfig jazz_online_cmn_cfg.proto
start_min_frame : 15
post_update_frame : 15
left_seek_frame : 15
min_flush_frame : -1
win_size : 0
smooth : 1
feature_dim : 40
channel_number : 1
win : 5
skip_frame : 0
cache_size : 1
